[build]
dist = "dist"

[[copy]]
source = "assets"
destination = "assets"

[[copy]]
source = "static"
destination = "static"


[watch]
watch = ["src", "static"]

[serve]
address = "0.0.0.0"
port = 8080
open = true
headers = { "ngrok-skip-browser-warning" = "true" }
